# @serviceUrl = https://api.acik-kaynak.org
@serviceUrl = http://localhost:3000

##
## GRAPHQL
##

POST {{serviceUrl}}/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  user(id: "eser") {
    name
  }
}

###

##
## AUTH
##

GET {{serviceUrl}}/auth/github
Content-Type: application/json

###

GET {{serviceUrl}}/auth/githubCallback?code=2349244da729070e012c&state=
Content-Type: application/json

###

##
## GITHUB
##

GET {{serviceUrl}}/github/profile
Content-Type: application/json
Authorization: token
